name : Test yml

on: push

jobs: 
  job1: 
    name: First job1
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    run: echo This is first Job
      
  job2:
    name: Second job
    runs-on: ubuntu-latest
    steps: 
    - name: Run a one-line script
      run: echo Hello, World!
